workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Codemagic_API_Key  # Uses automatic signing

    environment:
      ios_signing:
        distribution_type: development  # Set to "app_store" for production
        bundle_identifier: com.joanakibode.storycal

    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
      - name: Prebuild Expo app
        script: |
          npx expo prebuild --platform ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up automatic signing
        script: |
          xcode-project use-profiles
      - name: Build iOS App
        script: |
          xcode-project build-ipa --workspace "ios/StoryCal.xcworkspace" --scheme "StoryCal"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - jakibode@outlook.fr
        notify:
          success: true
          failure: true
