workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: Codemagic_API_Key  # Apple API key set in Codemagic UI

    environment:
      ios_signing:
        distribution_type: development    # ✅ For TestFlight
        bundle_identifier: com.joanakibode.storycal
      vars:
        XCODE_WORKSPACE: "StoryCal.xcworkspace"
        XCODE_SCHEME: "StoryCal"
        APP_ID: 6742653857  # From App Store Connect
        EXPO_TOKEN: $EXPO_TOKEN  # Optional, for future EAS-related features
        NODE_VERSION: 18.19.0
        RUBY_VERSION: 3.2.2
      node: 18.19.0
      xcode: latest
      cocoapods: default

    scripts:
      - name: Remove conflicting lockfile
        script: |
          rm -f package-lock.json

      - name: Install dependencies, Expo CLI and eject app
        script: |
          yarn install
          yarn global add expo-cli
          expo prebuild --platform ios  # replaces expo eject

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/ios/StoryCal/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy

          if ! $PLIST_BUDDY -c "Print :ITSAppUsesNonExemptEncryption" "$PLIST" > /dev/null 2>&1; then
            $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST"
          else
            echo "ITSAppUsesNonExemptEncryption already exists in Info.plist"
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install --verbose --repo-update

      - name: Set up automatic signing
        script: |
          xcode-project use-profiles --warn-only

      - name: Create exportOptions.plist
        script: |
          cat > ios/exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>teamID</key>
              <string>286X5G8B98</string>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          EOF

      - name: Build ipa for distribution
        script: |
          # Set up build directories
          BUILD_DIR="$CM_BUILD_DIR/build"
          ARCHIVE_PATH="$BUILD_DIR/StoryCal.xcarchive"
          IPA_PATH="$BUILD_DIR/ios/ipa"
          
          # Create necessary directories
          mkdir -p "$BUILD_DIR"
          mkdir -p "$IPA_PATH"
          
          # Clean previous builds
          cd $CM_BUILD_DIR/ios
          xcodebuild clean -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME"
          
          # Archive the app
          echo "Starting archive process..."
          xcodebuild archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath "$ARCHIVE_PATH" \
            CODE_SIGN_STYLE=Automatic \
            DEVELOPMENT_TEAM=286X5G8B98 \
            COMPILER_INDEX_STORE_ENABLE=NO \
            -destination "generic/platform=iOS" \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES \
            | xcpretty
          
          # Check if archive was created
          if [ ! -d "$ARCHIVE_PATH" ]; then
            echo "Error: Archive was not created at $ARCHIVE_PATH"
            exit 1
          fi
          
          echo "Archive created successfully at $ARCHIVE_PATH"
          
          # Export the archive
          echo "Starting export process..."
          xcodebuild -exportArchive \
            -archivePath "$ARCHIVE_PATH" \
            -exportOptionsPlist exportOptions.plist \
            -exportPath "$IPA_PATH" \
            | xcpretty
          
          # Check if IPA was created
          if [ ! -d "$IPA_PATH" ] || [ ! -f "$IPA_PATH"/*.ipa ]; then
            echo "Error: IPA was not created in $IPA_PATH"
            exit 1
          fi
          
          echo "Build completed successfully"
          ls -la "$IPA_PATH"
              
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - jakibode@outlook.fr
        notify:
          success: true
          failure: true
