workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - ENV-VAR  # This group should contain your EXPO_TOKEN
      vars:
        EXPO_TOKEN: $EXPO_TOKEN  # This will use the EXPO_TOKEN from the ENV-VAR group
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Test environment variables
        script: |
          echo "Testing environment variable expansion:"
          echo "EXPO_TOKEN exists: $([[ -n $EXPO_TOKEN ]] && echo 'yes' || echo 'no')"
          
      - name: Install dependencies
        script: |
          # Clean install to avoid cache issues
          rm -rf node_modules
          # Install dependencies with legacy peer deps to handle warnings
          npm install --legacy-peer-deps
      - name: Set up EAS
        script: |
          # Install EAS CLI
          echo "Installing EAS CLI..."
          npm install -g eas-cli
          
          # Debug: Print EAS CLI version
          echo "EAS CLI version:"
          eas --version
          
          # Debug environment
          echo "Environment debugging:"
          echo "Shell: $SHELL"
          echo "PWD: $PWD"
          
          # Verify EXPO_TOKEN without exposing it
          if [ -z "$EXPO_TOKEN" ]; then
            echo "Error: EXPO_TOKEN is not set"
            exit 1
          else
            TOKEN_LENGTH=${#EXPO_TOKEN}
            echo "EXPO_TOKEN length: $TOKEN_LENGTH"
            echo "First character: ${EXPO_TOKEN:0:1}"
            echo "Last character: ${EXPO_TOKEN: -1}"
            
            if [ $TOKEN_LENGTH -ne 40 ]; then
              echo "WARNING: Token length ($TOKEN_LENGTH) is not the expected 40 characters"
              echo "This suggests the token might not be set correctly in Codemagic"
              exit 1
            fi
          fi
          
          # Attempt to login with token
          echo "Logging in to EAS..."
          eas login --token "$EXPO_TOKEN"
          
          # Verify login status
          echo "Verifying EAS login status..."
          eas whoami
      - name: Build iOS app
        script: |
          echo "Starting iOS build..."
          eas build --platform ios --profile development --non-interactive --json
    artifacts:
      - "*.ipa"
      - "*.app"
      - "build/ios/ipa/*.ipa"
      - "/tmp/xcodebuild_logs/*.log"
      - "$HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app"
      - "$HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM" 