workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - ENV-VAR  # Contains EXPO_TOKEN
      vars:
        BUNDLE_ID: "com.joanakibode.mystory"
      node: latest
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install --legacy-peer-deps
          npm install -g eas-cli
          
      - name: Set up EAS
        script: |
          # Verify and use EXPO_TOKEN
          if [ -n "$EXPO_TOKEN" ]; then
            TOKEN_TO_USE="$EXPO_TOKEN"
          elif [ -n "$CM_EXPO_TOKEN" ]; then
            TOKEN_TO_USE="$CM_EXPO_TOKEN"
            echo "Using CM_EXPO_TOKEN instead of EXPO_TOKEN"
          else
            echo "Error: Neither EXPO_TOKEN nor CM_EXPO_TOKEN is set"
            exit 1
          fi
          
          # Login to EAS
          eas login --token "$TOKEN_TO_USE"
          
      - name: Build iOS app
        script: |
          # Build using EAS
          eas build --platform ios --profile development --non-interactive
          
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - joanakibode@gmail.com
        notify:
          success: true
          failure: true
