workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: |
          # Clean install to avoid cache issues
          rm -rf node_modules
          # Install dependencies with legacy peer deps to handle warnings
          npm install --legacy-peer-deps
      - name: Set up EAS
        script: |
          # Install EAS CLI
          echo "Installing EAS CLI..."
          npm install -g eas-cli
          
          # Debug: Print EAS CLI version
          echo "EAS CLI version:"
          eas --version
          
          # Debug environment
          echo "Environment debugging:"
          echo "Shell: $SHELL"
          echo "PWD: $PWD"
          echo "All environment variables (names only):"
          env | cut -d= -f1
          
          # Verify EXPO_TOKEN without exposing it
          if [ -z "$EXPO_TOKEN" ]; then
            echo "Error: EXPO_TOKEN is not set"
            exit 1
          else
            TOKEN_LENGTH=${#EXPO_TOKEN}
            echo "EXPO_TOKEN length: $TOKEN_LENGTH"
            echo "First character: ${EXPO_TOKEN:0:1}"
            echo "Last character: ${EXPO_TOKEN: -1}"
            echo "Contains underscore: $(echo $EXPO_TOKEN | grep -c "_")"
            echo "Number of characters before first underscore: $(echo $EXPO_TOKEN | cut -d'_' -f1 | wc -c)"
            echo "Number of parts split by underscore: $(echo $EXPO_TOKEN | tr -cd '_' | wc -c)"
            
            if [ $TOKEN_LENGTH -ne 40 ]; then
              echo "WARNING: Token length ($TOKEN_LENGTH) is not the expected 40 characters"
              echo "This suggests the token might not be set correctly in Codemagic"
            fi
          fi
          
          # Try reading token from environment file
          echo "EXPO_TOKEN=$EXPO_TOKEN" > .env.tmp
          echo "Token from file length: $(cat .env.tmp | cut -d= -f2 | wc -c)"
          rm .env.tmp
          
          # Attempt to login with token
          echo "Logging in to EAS..."
          export EXPO_TOKEN="$EXPO_TOKEN"
          eas login --token "$EXPO_TOKEN"
          
          # Verify login status
          echo "Verifying EAS login status..."
          eas whoami
      - name: Build iOS app
        script: |
          echo "Starting iOS build..."
          eas build --platform ios --profile development --non-interactive --json
    artifacts:
      - "*.ipa"
      - "*.app"
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM 