workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        EXPO_TOKEN: ${EXPO_TOKEN}
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    ssh_access:
      enabled: true    # Enables SSH/VNC access for debugging
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set up EAS
        script: |
          npm install -g eas-cli
          eas login --token ${EXPO_TOKEN}
      - name: Build iOS app
        script: |
          eas build --platform ios --profile development --non-interactive
    artifacts:
      - "*.ipa"
      - "*.app"
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM 