workflows:
  expo-ios:
    name: Expo iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - ENV-VAR  # This group should contain your EXPO_TOKEN
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Test environment variables
        script: |
          echo "Testing environment variable expansion:"
          echo "EXPO_TOKEN exists: $([[ -n $EXPO_TOKEN ]] && echo 'yes' || echo 'no')"
          echo "CM_EXPO_TOKEN exists: $([[ -n $CM_EXPO_TOKEN ]] && echo 'yes' || echo 'no')"
          
      - name: Install dependencies
        script: |
          # Clean install to avoid cache issues
          rm -rf node_modules
          # Install dependencies with legacy peer deps to handle warnings
          npm install --legacy-peer-deps
          
      - name: Set up EAS
        script: |
          # Install EAS CLI
          echo "Installing EAS CLI..."
          npm install -g eas-cli
          
          # Debug: Print EAS CLI version
          echo "EAS CLI version:"
          eas --version
          
          # Debug environment
          echo "Environment debugging:"
          echo "Shell: $SHELL"
          echo "PWD: $PWD"
          
          # Verify EXPO_TOKEN without exposing it
          if [ -n "$EXPO_TOKEN" ]; then
            TOKEN_TO_USE="$EXPO_TOKEN"
          elif [ -n "$CM_EXPO_TOKEN" ]; then
            TOKEN_TO_USE="$CM_EXPO_TOKEN"
            echo "Using CM_EXPO_TOKEN instead of EXPO_TOKEN"
          else
            echo "Error: Neither EXPO_TOKEN nor CM_EXPO_TOKEN is set"
            exit 1
          fi
          
          TOKEN_LENGTH=${#TOKEN_TO_USE}
          echo "Token length: $TOKEN_LENGTH"
          echo "First character: ${TOKEN_TO_USE:0:1}"
          echo "Last character: ${TOKEN_TO_USE: -1}"
          
          if [ $TOKEN_LENGTH -ne 40 ]; then
            echo "WARNING: Token length ($TOKEN_LENGTH) is not the expected 40 characters"
            echo "This suggests the token might not be set correctly in Codemagic"
            exit 1
          fi
          
          # Attempt to login with token
          echo "Logging in to EAS..."
          eas login --token "$TOKEN_TO_USE"
          
          # Verify login status
          echo "Verifying EAS login status..."
          eas whoami
          
      - name: Build iOS app
        script: |
          echo "Starting iOS build..."
          eas build --platform ios --profile development --non-interactive --json
          
    artifacts:
      - "*.ipa"
      - "*.app"
      - "build/ios/ipa/*.ipa"
      - "/tmp/xcodebuild_logs/*.log"
      - "$HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app"
      - "$HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM"
